### ISSUE TITLE
Node can't find  camera0.m3u8

### ISSUE THREAD

**Issue by fvgtekken** [erceth/OPENCV-FFMPEG-HLS-VMS-JS-PY-public#1]
Hello! Thanks  create this repo! it is very helpful, but when i tryed to run the repo is throwing the following error:

$ node index.js
starting stream0
Error: ENOENT: no such file or directory, unlink 'camera0.m3u8'
    at Object.unlinkSync (fs.js:1053:3)
    at removeOldRecordings (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\index.js:162:8)
    at startStream (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\index.js:35:3)
    at E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\index.js:23:3
    at arrayEach (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\node_modules\lodash\lodash.js:530:11)
    at Function.forEach (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\node_modules\lodash\lodash.js:9410
:14)
    at Object.<anonymous> (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\index.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  errno: -4058,
  syscall: 'unlink',
  code: 'ENOENT',
  path: 'camera0.m3u8'
}
FFmpeg command redacted. Fill in yourself or contact author.
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [ '-re', '-stream_loop', -1 ]
}
$ node index.js
starting stream0
Error: ENOENT: no such file or directory, unlink 'camera0.m3u8'
    at Object.unlinkSync (fs.js:1053:3)
    at removeOldRecordings (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\index.js:162:8)
    at startStream (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\index.js:35:3)
    at E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\index.js:23:3
    at arrayEach (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\node_modules\lodash\lodash.js:530:11)
    at Function.forEach (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\node_modules\lodash\lodash.js:9410
:14)
    at Object.<anonymous> (E:\Projectos\Intel\front-end-app\help\OPENCV-FFMPeG-HLS-VMS-JS-PY-public\index.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  errno: -4058,
  syscall: 'unlink',
  code: 'ENOENT',
  path: 'camera0.m3u8'
}
FFmpeg command redacted. Fill in yourself or contact author.
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [ '-re', '-stream_loop', -1 ]
}

And I'm  using only one camera with the following config:
  cameras: [
    {
      ip: "bitdash-a.akamaihd.net",
      path: "/vod/mp4:BigBuckBunny_115k.mov",
      detectParameters: {
        inputFps: 30,
        detectFps: 3,
        width: 240,
        height: 160,
        minPixelSize: 5000,
        motionDeltaThreshold: 5,
        motionPaddingCutoutPercent: 0.2,
        cutOutHeightLimit: 150,
        checkNLargestObjects: 1,
        windowStride: 4,
        hogPadding: 4,
        hogScale: 1.05,
        hogHitThreshold: 0,
        nonMaxSuppressionThreshold: 0.65,
      },
    },
  ],

pd: Do you have a list of commands for ffmpeg to provide?
console.log('FFmpeg command redacted. Fill in yourself or contact author.')
const command = [];

Thank you in advance!

**Comment by erceth** [comment]
I made public the repo that contains the ffmpeg command. Try using that repo instead:
https://github.com/erceth/OPENCV-FFMPEG-HLS-VMS-JS-PY
